name: consumer-snap
version: '0.1'
summary: Consumes content snap files
description: This consumes the other snaps files
grade: stable
confinement: strict

plugs:
  content:
    interface: content
    content: config
    target: $SNAP/config

apps:
  consumer-snap:
    command: bash
parts:
  nothing:
    plugin: nil
    override-pull: echo "nothing to pull"