name: producer-snap1
version: '0.1'
summary: Produces content snap files
description: This produces other snaps files t be consumed by the consumer
grade: stable
confinement: strict

slots:
  content:
    interface: content
    content: config    
    read:
      - $SNAP/config1

apps:
  producer-snap1:
    command: bash
parts:
  config:
    plugin: dump
    source: .
    stage:
      - config/*